jwt:
  secret: testtesttesttesttesttesttesttest

spring:
  data:
    mongodb:
      port: ${MONGO_DB_PORT}
      host: ${MONGO_DB_URL}
      auto-index-creation: true
      authentication-database: admin
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}