version: '3'

services:
  user-service:
    networks:
      - testchat
    image: testchat-user
    command:
      -
    build:
      context: .
      dockerfile: './user/Dockerfile'
    ports:
      - "8030:8030"
    container_name: chat-user-backend
    environment:
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
  chat-service:
    networks:
      - testchat
    image: testchat-chat
    build:
      context: .
      dockerfile: './chatting/Dockerfile'
    ports:
      - "8030:8030"
    container_name: chat-backend
    environment:
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_URL: ${MONGO_DB_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}

networks:
  testchat: