jwt:
  secret: testtesttesttesttesttesttesttest
spring:
  data:
    mongodb:
      password: hong
      username: hong
      authentication-database: admin
      auto-index-creation: true
      database: chattest
      host: 211.38.86.92
      port: 27017
  rsocket:
    server:
      port: 7001
      mapping-path: /rsocket
      transport: websocket
  security:
    user:
      name: test
  rabbitmq:
    port: 5672
    host: localhost

server:
  port: 8031
logging:
  level:
    org.springframework.data.mongodb.repository.query: DEBUG
